var searchData=
[
  ['adjointderivative_5fff_0',['AdjointDerivative_FF',['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#a659368b64a291f3666ef1743136d564e',1,'BAEMM::Helmholtz_OpenCL']]],
  ['applyboundaryoperators_5fpl_1',['ApplyBoundaryOperators_PL',['../class_b_a_e_m_m_1_1_helmholtz___c_p_u.html#ab54c0bbe751e081303d8c43405ddde4c',1,'BAEMM::Helmholtz_CPU::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out, cptr&lt; R_ext &gt; kappa_list, cptr&lt; C_ext &gt; coeff_list, const I_ext wave_count_, const I_ext wave_chunk_size_)'],['../class_b_a_e_m_m_1_1_helmholtz___c_p_u.html#a577190545297bcea8dce99c022bd843a',1,'BAEMM::Helmholtz_CPU::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in_, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out_)'],['../class_b_a_e_m_m_1_1_helmholtz___metal.html#a884b8b2504a5d3f784f28796883b09f4',1,'BAEMM::Helmholtz_Metal::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out, cptr&lt; R_ext &gt; kappa_list, cptr&lt; C_ext &gt; coeff_list, const I_ext wave_count_, const I_ext wave_chunk_size_)'],['../class_b_a_e_m_m_1_1_helmholtz___metal.html#a26b8528a0110a59d9cd0968b6c02ad6f',1,'BAEMM::Helmholtz_Metal::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in_, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out_)'],['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#ab06b6577dc26c9ab411a853fb919ab22',1,'BAEMM::Helmholtz_OpenCL::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out, cptr&lt; R_ext &gt; kappa_list, cptr&lt; C_ext &gt; coeff_list, const I_ext wave_count_, const I_ext wave_chunk_size_)'],['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#a54530cdb083f28eddab92a99dba6cf56',1,'BAEMM::Helmholtz_OpenCL::ApplyBoundaryOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in_, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out_)']]],
  ['applyfarfieldoperators_5fpl_2',['ApplyFarFieldOperators_PL',['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#ae96ebc1f271dadf2eaccb4e0efa8149d',1,'BAEMM::Helmholtz_OpenCL::ApplyFarFieldOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out, const R_ext *kappa_list, const C_ext *coeff_list, const I_ext wave_count_, const I_ext wave_chunk_size_)'],['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#a8b383bcb536a3c6b663ec6cf68fc35fb',1,'BAEMM::Helmholtz_OpenCL::ApplyFarFieldOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in_, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out_)']]],
  ['applylumpedmassinverse_3',['ApplyLumpedMassInverse',['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#afccfe7216e28121dbe406df72d805354',1,'BAEMM::Helmholtz_OpenCL']]],
  ['applymassinverse_4',['ApplyMassInverse',['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#ad95e2eb4c733b5d374b163c2ed9eb8af',1,'BAEMM::Helmholtz_OpenCL']]],
  ['applynearfieldoperators_5fpl_5',['ApplyNearFieldOperators_PL',['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#ad5ad286a79c3f51e2447acaa8ded46ce',1,'BAEMM::Helmholtz_OpenCL::ApplyNearFieldOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out, const R_ext *kappa_list, const C_ext *coeff_list, const I_ext wave_count_, const I_ext wave_chunk_size_, const R_ext *evaluation_points_, const I_ext evaluation_count_)'],['../class_b_a_e_m_m_1_1_helmholtz___open_c_l.html#a676b142db2da4e8755356f62644e7c4c',1,'BAEMM::Helmholtz_OpenCL::ApplyNearFieldOperators_PL(const C_ext alpha, cptr&lt; C_ext &gt; B_in, const I_ext ldB_in_, const C_ext beta, mptr&lt; C_ext &gt; C_out, const I_ext ldC_out_, const R_ext *evaluation_points_, const I_ext evaluation_count_)']]]
];
